name: Github Release Workflow

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/checkout@v3

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: Build All APKs
        id: build
        run: |
          # Build release variants
          bash ./gradlew assembleTempoRelease
          bash ./gradlew assembleNotquitemyRelease
          # Build debug variants  
          bash ./gradlew assembleTempoDebug
          bash ./gradlew assembleNotquitemyDebug

      - name: Sign Tempo Release APKs
        id: sign_tempo_release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/tempo/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS_GITHUB }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD_GITHUB }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Sign NotQuiteMy Release APKs
        id: sign_notquitemy_release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/notquitemy/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS_GITHUB }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD_GITHUB }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ github.ref }}
          body: '> Changelog coming soon'
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release APKs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.sign_tempo_release.outputs.signedReleaseFile}}
          asset_name: app-tempo-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload NotQuiteMy Release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.sign_notquitemy_release.outputs.signedReleaseFile}}
          asset_name: app-notquitemy-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Debug APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: |
            app/build/outputs/apk/tempo/debug/
            app/build/outputs/apk/notquitemy/debug/
          retention-days: 30

      - name: Upload Release APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: |
            ${{steps.sign_tempo_release.outputs.signedReleaseFile}}
            ${{steps.sign_notquitemy_release.outputs.signedReleaseFile}}
          retention-days: 30